packages:
  - apps/*
  - packages/*
  - components/**

ignoredBuiltDependencies:
  - esbuild

overrides:
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  tmp@<=0.2.3: '>=0.2.4'
